### ISSUE TITLE
Score keeping aperatus

### ISSUE THREAD

**Issue by Wollivan** [Wollivan/SquadronLeader#14]
Rather than relying on the possession of a pen and pad, create something that can help players see which plane has what stats.

This could also be integrated into a storage solution.

**Comment by Teque5** [comment]
Yea there should be an elegant 3d-printed solution for this.

**Comment by Wollivan** [comment]
There's been a few ideas floated on the Reddit posts, so I am going to have a think, but there is no reason why all the options are available to print (dials, counters etc)

**Comment by amnos0405** [comment]
Someone posted a design up on reddit for a stat tracker. I got inspired by it and created a test. Let me know what y'all think or any possible improvements. My one thought is that if a printer is not dialed in correctly the numbers will not be too clear. Printing them number side down helps though. I'd be happy to make a branch for a pull once ideas have been thrown around.

![20220515_222150](https://user-images.githubusercontent.com/10867382/168509876-f9147cdb-f389-49aa-ba5b-3ab27716aaac.jpg)
![20220515_222252](https://user-images.githubusercontent.com/10867382/168509882-8556a327-250f-4030-bd97-9b2f409c3efd.jpg)

**Comment by Wollivan** [comment]
Wow this is amazing! Really neat idea, and great thinking about printability on all printers.

You could also use dots instead of numbers if that would be clearer?

**Comment by lifelike** [comment]
That looks so good I think it will make the entire game look much more fun when set up!

One thought is that, since it is printed in 3D and all, it is probably possible to make the display so that it hides all the digits (or, well dots) except for the relevant one? If the tokens with digits are thinner than the display they could be slotted in below it so that only one digit is visible in a window. Or one digit could protrude below the display with the rest hidden. Makes the display slightly bigger, but I think it looks a bit busy with all the digits visible.

**Comment by Wollivan** [comment]
Also just to add, I love these symbols and can't wait to print my set of these!

If you don't make it with dots, please keep the version with numbers too :)

**Comment by amnos0405** [comment]
> If the tokens with digits are thinner than the display they could be slotted in below it so that only one digit is visible in a window. Or one digit could protrude below the display with the rest hidden. Makes the display slightly bigger, but I think it looks a bit busy with all the digits visible.

Great idea and good eye lifelike, it is very busy with all numbers showing. I've got an idea in my head on how to implement the hidden slot without making the display too much bigger.

> Also just to add, I love these symbols and can't wait to print my set of these!

> If you don't make it with dots, please keep the version with numbers too :)

Wollivan, i'll make a branch tonight with the stls so folks can get a feel for them if wanted... And dots...

**Comment by lifelike** [comment]
Had another thought that maybe it is possible to make slots along one side to track remaining life with some kind of arrow/triangle thing moved down. Similar to the slots along the "bottom" side, but smaller. Possibly more ergonomic to move a small marker down to the next slot when hit compared to rotating one of those bigger markers.

**Comment by Wollivan** [comment]
Hey one more thought I had, the numbers don't need to all be present on the counters, you could just have one big number in the middle, and make one 2, two 3s and a 4.

**Comment by amnos0405** [comment]
A bit of a combination of everyone's ideas... I tried the concealing idea and it got too crammed/complex. Thoughts on accessibility/language of dots vs numbers? Or let's keep both!

![statTest2a](https://user-images.githubusercontent.com/10867382/168725334-767f4814-b006-4e28-a19a-5ee1af51de37.png)
![statTest2b](https://user-images.githubusercontent.com/10867382/168725348-ea200555-4c6e-4cb9-ae04-4c1bafa07173.png)

Making a pull request now, would like to hear feedback before it's merged in.

**Comment by lifelike** [comment]
My 2c: I am not a fan of using dots like that, because of how it looks like dice. To me it implies some value to roll ("roll 3+ to hit"), not "this is how many dice you need to roll" or "this is how much health this plane has".

**Comment by Wollivan** [comment]
> Thoughts on accessibility/language of dots vs numbers? Or let's keep both!

I think keep both, just give people a choice.

In regards to language, I'm happy to be corrected here, but I believe those numbers have become ubiquitous, but again happy to be wrong!

**Comment by Wollivan** [comment]
Also I like the life counter notches :)

**Comment by amnos0405** [comment]
First test print of all the pieces. Happy with most of it, going to make a few small tweaks (dots too high, width of board needs to reduce by ~1mm so it fits standing in the box). Doing a play test today at lunch for a real world experience, table flipping and all.

![20220517_084848](https://user-images.githubusercontent.com/10867382/168818094-260d39fa-3f0f-4298-a8b4-d8e14b9b3c8f.jpg)
![20220517_084857](https://user-images.githubusercontent.com/10867382/168818121-2a6967f3-2986-42f4-8622-d1b54bb0558d.jpg)
![20220517_085606](https://user-images.githubusercontent.com/10867382/168818129-30d43d09-1646-4fe1-8b43-76b9c1a2108f.jpg)

**Comment by Wollivan** [comment]
Off topic, but is that the bendable range ruler?!

**Comment by Wollivan** [comment]
This is so cool, I flipping love al the colours, really grateful for all you've added to the game (so far)!

**Comment by Wollivan** [comment]
> It is! Printed with TPU...but by TPU's nature the numbers on it are stringy and not very crisp. Also if that thing has room to expand quickly in the box, pieces can go flying (it has caused a scavenger hunt for dice a couple of times already). I would say a hard ruler that can snap together with dovetailing, etc, would be better.

Well I had better add it back to the files then because I removed it!

> I saw the post on Reddit and fell in love with the game (I'm a sucker for small box games too). It's been super fun to collaborate on with everyone. It's shown me I should learn OpenSCAD though, as Blender is not best for customizations/collaboration.

Yeah it's been so fun and weird working with people I've never met on something I've spent months dreaming up. It's been so rewarding, I was blown away by the initial response on Reddit. Thinking of making a new Reddit post soon with an update, but want it to be meaningful!

Did you get a chance to play with your designs today?

**Comment by amnos0405** [comment]
I did play with my coworker today at lunch, twice actually (I won both thank you). He really enjoyed it too, and he's familiar with X Wing. Said this was a great lightweight reimagining. He understood the rules well too.

As for the pieces, they needed some adjustment. They have no weight to hold themselves down so any table shake or fumbling fingers can cause havoc. He had a great idea for the health tracker and I noodled with the stat chits...printing a quick proof of the changes now.

**Comment by amnos0405** [comment]
Ok, final iteration I think. Very happy with it's stability and trimness. I'll post the full on glamour shots on Reddit.

![20220519_140920](https://user-images.githubusercontent.com/10867382/169373494-1542e6af-b01c-4fca-a270-4d6f26a4b4a5.jpg)
![20220519_141012](https://user-images.githubusercontent.com/10867382/169373557-36cbf422-12d4-4e15-9e37-f7d218d62c75.jpg)

**Comment by Wollivan** [comment]
Oh boy, these are so good looking! Excellent work!

If you're up for it. Big if. Pictures of your set always look amazing, and the website would benefit from a shot of all your components together top down. If you are willing to take one of course!

**Comment by Wollivan** [comment]
How did you do the grey inside the numbers?

**Comment by amnos0405** [comment]
I'll definitely take some top down shots for you.

The grey inside is achieved by setting a filament swap in the slicer...then another back to the original color after the grey layer.

![FilamentSwap1](https://user-images.githubusercontent.com/10867382/169403964-ae9f172d-b6d7-401e-bc99-44f08776dd48.png)

![FilamentSwap2](https://user-images.githubusercontent.com/10867382/169403980-d5b6bb48-d4e8-46a3-8db0-d8df2b889105.png)

Also there's another branch to merge =)

**Comment by amnos0405** [comment]
@Wollivan got some top down shots, let me know if these work well. Also really like the dovetail ruler, already substituted out the bendy one.

![20220520_163314](https://user-images.githubusercontent.com/10867382/169609138-6a2785b3-7207-411e-9ec9-f6984a9fde36.jpg)

![20220520_163327](https://user-images.githubusercontent.com/10867382/169609156-1f6f9d02-0d03-4b1a-ac28-3ca0a498abaa.jpg)

![20220520_164148](https://user-images.githubusercontent.com/10867382/169609173-a45732b1-c025-4ea2-bad3-fe35b538bff9.jpg)

**Comment by Wollivan** [comment]
> @Wollivan got some top down shots, let me know if these work well. Also really like the dovetail ruler, already substituted out the bendy one.

Greg these are incredible, this looks so freaking good!

**Comment by Wollivan** [comment]
I'm going to close this issue because I love what you've made Greg!

If anyone else has made alternatives don't think me closing this issue means you can't share it!
