### ISSUE TITLE
Printable storage

### ISSUE THREAD

**Issue by Wollivan** [Wollivan/SquadronLeader#15]
It would be ideal for people who are printing a copy to be able to have a purpose built box to store their game.

**Comment by amnos0405** [comment]
Working on a custom topper that is traced from the Squadron Leader tin (i posted on the Reddit thread). Figured the [tin here](https://www.thingiverse.com/thing:713187) could be used and my topper just glued on.

**Comment by Wollivan** [comment]
Someone beat you to the punch, and I thought it was you!

Please don't stop though, looking forward to the plane box!

**Comment by amnos0405** [comment]
No worries @Winehorn. Like your clean and simple to print design. I'll still finish mine because variety is the spice of life, plus I'm having fun with it.

**Comment by Wollivan** [comment]
Hey @amnos0405 @Winehorn are you both happy with your representation in the box files on the repo?

If you are I will close the issue, but no pressure if you're still working on yours!

**Comment by Wollivan** [comment]
@Winehorn could I ask a huge favour of you, to upload the box and lid as separate STLs?

**Comment by amnos0405** [comment]
@Wollivan I'm good with you closing the issue.
