### ISSUE TITLE
Please add a LICENSE to this repository

### ISSUE THREAD

**Issue by penyuan** [Wollivan/SquadronLeader#2]
What a great game! Thanks for publishing it here.

However, there is no `LICENSE` file in this repository, and because of that others are not allowed to study, share, and build on these files/designs. Please follow these [easy instructions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) in GitHub's documentation to choose and apply a proper open source license for this package, such as the CC BY-SA 4.0 license. Thanks!

If it helps, I'd be happy to send a pull request with the needed changes.

**Comment by Wollivan** [comment]
Hey! Sorry I didn't see this, I've just added the license to the bottom of the readme, and I now need to get some sleep, but if you are happy to make a PR for the necessary changes I'd be very grateful!!

**Comment by penyuan** [comment]
Thanks! I've submitted a pull request [here](https://github.com/Wollivan/SquadronLeader/pull/5).

**Comment by Wollivan** [comment]
So useful, have merged the PR, thank you!
