### ISSUE TITLE
Hexagons are the Bestagons

### ISSUE THREAD

**Issue by Teque5** [Wollivan/SquadronLeader#23]
I started remixing this design for a hexagon-based layout (since clearly we all love hexagons), but I'm wondering if the reduction in the firing arc from 90° to 60° will have a large adverse effect on gameplay. I'm printing your original design now (with some tweaks) so I have yet to actually play this.
![hex](https://user-images.githubusercontent.com/784749/167316992-51542d00-3310-4796-b97c-0ce759ae7d01.jpg)

**Comment by Wollivan** [comment]
I don't think it would have a negative effect on gameplay no, it would just make it more challenging, and maybe that's a good thing?

**Comment by Wollivan** [comment]
Great idea by the way!

**Comment by Wollivan** [comment]
lifelike just made a pull request that's similar to what you're working on.

I've merged it, so it's on main now, have a look and see what came up with that was different/the same.

I will add a model tomorrow that has a 60 firing arc, and still leave the 90 on there, but you have got me thinking about whether it should be 60 instead.

**Comment by Wollivan** [comment]
Sorry for spamming, I'd love to see all the tweaks to the models, perhaps they should be the default!

**Comment by lifelike** [comment]
I don't really think what I did with the hex grid is similar to this. If anything it is actually quite annoying to have hex-shaped playing pieces moving on a hex grid, so the rectangular ones were just fine. Plus the arc of fire that I came up with is closer to 90-degrees in the hex grid rules.

That model looks nice though. I guess the movement templates has to be modified as well to fit this shape?

**Comment by Wollivan** [comment]
You know I didn't even notice the model in the first comment was Hexagon! I did like the look of it though, a cleaner look maybe?

I think for the hex grid rules the model doesn't HAVE to change, but I don't want anyone to have wasted time making anything, so always make a PR, even if it just goes to another modular rule set or something.

The more the merrier!

**Comment by Teque5** [comment]
I finished printing the original design but soon realized it didn't fit in an altoids tin, only that larger out-of-print Squadron Leader Tin size. With that in mind I went back just now and did some simulated packing to see if I could **actually** fit everything in a single modern tin.

If we scale the hexagons to 22x25.4x2ish mm then it would be possible to put (6) players worth of airplanes, (12) 12mm d6 small dice, and all (3) movement pieces into the interior space of a normal tin. I think (?) a string would also fit.
![2022-05-10_packing-sim_0sm](https://user-images.githubusercontent.com/784749/167769710-0509bf5f-61a7-4df8-a235-b6e86d8c04f5.png)
![2022-05-10_packing-sim_1sm](https://user-images.githubusercontent.com/784749/167769708-34326191-8c9d-4626-bcdf-8c157919b68d.png)

If people are interested I can move forward. I would need to design the movement cards and a tin insert. For the movement cards I'm not exactly sure how long the (1,2,3) move pieces should be relative to everything else? It looks like the length of the move 1 piece is like 3.5x the square size of the octagonal original but I dunno.

**Comment by Wollivan** [comment]
Wow this is incredible!!

If you want to let me know exactly how wide/tall you want the planes and altitude tokens (excluding the plane image and nubs) I can just export some STLs specifically that scale.

It's all done in OpenSCAD, so I can just scale it there rather than anyone having to redesign anything. It took me so long to get the maneuver templates to be mathematically satisfying.
They are all technically the same "length" just bent.

**Comment by Wollivan** [comment]
Wow this is incredible!!

If you want to let me know exactly how wide/tall you want the planes and altitude tokens (excluding the plane image and nubs) I can just export some STLs specifically that scale.

It's all done in OpenSCAD, so I can just scale it there rather than anyone having to redesign anything. It took me so long to get the maneuver templates to be mathematically satisfying.
They are all technically the same "length" just bent.

**Comment by Teque5** [comment]
Let me noodle on this a bit.

An issue with using the existing octagon move templates is that they would be too wide to fit in the available space. I think I can modify / create new move templates for hexagons that would actually fit.

**Comment by Wollivan** [comment]
I mean I can change size of the octogon :)

**Comment by Wollivan** [comment]
@Teque5 I loved the work you did on this!

I hope you don't mind me closing this issue as I've now made a printable box that fits everything 4 players need to play!
