### ISSUE TITLE
Turn Sequence

### ISSUE THREAD

**Issue by lifelike** [Wollivan/SquadronLeader#3]
From what I can see there is no part of the rules that explains what the order of things are? There is a Move Stage and an Attack Stage. Are they carried out in that order, by each player, or do all players move first and then all players attack? Or some other order? I think it needs to be clarified.

**Comment by Wollivan** [comment]
Great point, I will add some clarification today. to the rules!

Its everyone move in order, everyone attack in order btw :)

**Comment by Wollivan** [comment]
Fixed in PR 20 thanks!
