### ISSUE TITLE
Rearrange folder structure

### ISSUE THREAD

**Issue by Wollivan** [Wollivan/SquadronLeader#30]
I think it makes more sense to move the public and src folders and JSON files into a folder called client or website, so the GitHub page is less intimidating to people who are only interested in downloading the files.

**Comment by Wollivan** [comment]
Along with this, once its done I will create the website file structure to allow for multiple pages. That way if an expansion is ever created, it can have its own README file and a page that runs off that on the website.

**Comment by Wollivan** [comment]
Upon reflection, the website may benefit from being moved from Netlify to GitHub Pages.

That way it can be a lot more accessible for non technical when we reach the point of expansions, and maybe can make the home page a little smaller by splitting out the readme.

Would love to hear your thoughts.

**Comment by penyuan** [comment]
Not much to add other than one thing: 

Moving to GitHub Pages should be fine, but I suggest not coding the website in a way that strictly *locks* it into GitHub Pages and not being deployable anywhere else. Vendor lock-in can bite you if you're too dependent on it!

**Comment by Wollivan** [comment]
Great point! My main motivation is I want every bit of content to be editable by anyone.

The way it currently works doesn't actually prevent that, but it uses Sym links to get the content of the markdown to the website, which is a little messy I think. But it doesn't HAVE to change!

**Comment by Wollivan** [comment]
Does anyone have experience getting a scss/CSS file working with a GitHub Pages theme, that uses markdown not HTML?

As suggested, I don't want to get locked in to Pages, but if we can make a theme work with the current styles and layout it would be awesome.

I'm having no luck getting it to work on a dummy repo!

**Comment by Wollivan** [comment]
The current system uses a seperate React (NextJS in the works) site and pulls the content from pages in this repo.

I'm happy with this, so closing the issue.
