### ISSUE TITLE
Zeppelins and balloons

### ISSUE THREAD

**Issue by lifelike** [Wollivan/SquadronLeader#37]
There are no zeppelins in the game yet. Can this be tagged as a feature request? Balloons would be nice as well. Would be useful as targets both for p2p and solo scenarios.

**Comment by Winehorn** [comment]
Not just targets but also cover!

**Comment by Wollivan** [comment]
> Not just targets but also cover!

Great thinking!

Brilliant thought lifelike, I will start having a play with some models this evening/weekend!

**Comment by Wollivan** [comment]
@Winehorn @lifelike this is finally done!

https://squadronleader.wollivan.dev/expansions/bombers-balloons

A rule for cover is also inbound on the expansion README... because I forgot to add it!

**Comment by Winehorn** [comment]
Awesome stuff!
