### ISSUE TITLE
Maximum Altitude

### ISSUE THREAD

**Issue by lifelike** [Wollivan/SquadronLeader#4]
The rules make no mention of what the maximum altitude is. Each player is given 4 altitude tokens, so 4 is possibly the maximum? But the description of the Immelmann seems to imply 3 ("may gain 3 altitude tokens (or up to 3 if they already have 1, 2 or 3)"), or is it just that for some reason you will only be able to get to altitude 3 even if there is also a 4th altitude? Sounds like an unnecessary complication if that is the case?

**Comment by Wollivan** [comment]
Wow I can't believe I hadn't clarified this! I will update the altitude rules today, thank you!

**Comment by Wollivan** [comment]
Fixed in PR 21.
