### ISSUE TITLE
Someone with OctoPrint, could you film a set being printed for the website?

### ISSUE THREAD

**Issue by Wollivan** [Wollivan/SquadronLeader#41]
I'd like to put a gif at the top of the page showing the entire set being printed (not necessarily in one go) but I don't have the means to make a nice looking one.

**Comment by Winehorn** [comment]
I might have accidentally recorded my print 😁 will check tomorrow

**Comment by Wollivan** [comment]
> I might have accidentally recorded my print 😁 will check tomorrow

That is hilarious! Thanks Flo!

**Comment by Winehorn** [comment]
Might need to invest in some lighting 😄

**Comment by Wollivan** [comment]
Lol!! Very dark video?

**Comment by Winehorn** [comment]
Started the print in the evening, so [yeah](https://ibb.co/7v9k1JF) 😄

**Comment by Wollivan** [comment]
> Started the print in the evening, so [yeah](https://ibb.co/7v9k1JF) 😄

This is so funny haha!

**Comment by Winehorn** [comment]
Camera tired, camera going to sleeeep 😴

I'll maybe do another set this weekend and this time I'll do it in the morning 😉

**Comment by Wollivan** [comment]
Only do it if you want to, please don't feel like you have to just for the video!

**Comment by Winehorn** [comment]
Printed two stat trackers and the pluggable ruler today, will upload the video tomorrow 😊

**Comment by Wollivan** [comment]
> Printed two stat trackers and the pluggable ruler today, will upload the video tomorrow 😊

Thanks so much bro! Excited to see it!

**Comment by Winehorn** [comment]
[Here](https://ibb.co/RNQv8GY) you go! Have to work on the quality though. And on a mount for attaching the camera to the z-axis :D

**Comment by Wollivan** [comment]
Awesome thanks so much! 

I'll get this added to the website tonight :)

**Comment by Wollivan** [comment]
Finally got round to adding this so thank you! Closing the issue :)

**Comment by Wollivan** [comment]
No longer required, but thank you @Winehorn !
