### ISSUE TITLE
Multi colour pieces

### ISSUE THREAD

**Issue by Wollivan** [Wollivan/SquadronLeader#42]
Does anyone have the expertise to make a model specifically for multi colour printers to print planes that have a different colour top?

It's not something I've ever touched so if someone knows and is happy to make the files that would rock!

**Comment by Winehorn** [comment]
Not sure how it works for real multicolour printers but at least in PrusaSlicer I can specify a layer where the printer stops and waits for filament change. That should work perfectly with the plane models!

**Comment by Wollivan** [comment]
Oh nice! I just remembered I've done exactly that with Cura, can't believe I'd forgotten about that haha
