### ISSUE TITLE
Proposal: add small graphics to explain advanced maneuvers

### ISSUE THREAD

**Issue by asmialek** [Wollivan/SquadronLeader#47]
Hey, since I am a visual learner, some advanced maneuvers explanations were not so intuitive for me. I was thinking about adding some graphics (simple diagrams) to visualize what would they look like. If the example looks good, I could make some images for Split S, Barrel Roll, and Immelmann. Ofc the exact look needs a bit of brainstorming, but here is my proposal:
![image](https://user-images.githubusercontent.com/14300968/168493411-93cc51f9-c052-4fc2-984e-d42bfe99f72a.png)
(btw, I hope that I got it good in the end xD)

**Comment by Wollivan** [comment]
This is fantastic! Please do make a pull request I love it! If you add the images to [here](https://github.com/Wollivan/SquadronLeader/tree/main/src/assets/images) and I will add them to the website. Other wise there is a risk the images don't display properly on the front end.

My ONLY note would be to add the word "template" at the end of the sentence, other than that great idea!

If you also think any other rules would benefit from imagery feel free to make stuff like this, I REALLY love this!

**Comment by asmialek** [comment]
I'll produce some more and prepare a PR, I'm glad that you like it!

**Comment by Wollivan** [comment]
Thanks Adam, I can't wait!

**Comment by asmialek** [comment]
Added with #53. I can quickly change anything if you notice any problems when putting them on the website 😄  Also, would it make sense to upload a `.svg` file on which I worked to create these diagrams? And if yes, where?

**Comment by Wollivan** [comment]
So grateful thank you!

If you want to load SVGs, feel free to upload the SVGs in a new folder within the assets, maybe just called SVGs?

**Comment by Wollivan** [comment]
Going to close this issue, but if you want to make changes feel free to open it up.

These images are so great so thank you for the addition!!
