### ISSUE TITLE
Hex ranges illustration is incorrect

### ISSUE THREAD

**Issue by lifelike** [Wollivan/SquadronLeader#61]
In my latest PR that was accepted (thanks!) with rules for ranges on a hex grid, the illustration was not properly updated in the README and not sure how to fix. The image-links in the README uses some weird github-links and the one for hex fire arcs still refer to the old version, instead of the new that also illustrates the different ranges.

**Comment by Wollivan** [comment]
I will fix this in the morning  good spot!

**Comment by Wollivan** [comment]
All done, thanks for pointing it out Pelle!
